### PR TITLE
64 bit mac chromedriver

### PR DESCRIPTION
**Pull request by jwcacces**
Google supports a 64 bit chromedriver for mac
This adds that support

### CODE REVIEW

**Comment by alamsz** [comment]
@peterhudec chromedriver > 2.22 only has 64 bit architecture chromedriver in google repo and causing using pip install chromedriver_installer directly will fail, this PR fix that issue just fine

**Comment by fatjedi89** [comment]
any reason to delay this PR?

**Review by bhamodi — APPROVED** [review]

**Comment by bhamodi** [comment]
Would love to see this get merged in.

**Comment by mrichar1** [comment]
Looks like this was resolved in 9524628720dacd

**Pull request closed without merging**
